I misspelled a word in a string and got this:

pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'localhos' ([Errno 8] nodename nor servname provided, or not known)")


I added a new argument into the method and got this:

TypeError: __init__() missing 1 required positional argument: 'hello'


